import { Experience } from '@/types'

export const defaultExperience: Experience[] = [
  {
    id: '1',
    role: 'AI Research & Development Intern',
    company: 'National Institute of Technology Raipur',
    location: 'Raipur',
    period: 'May 2026 - Jul 2026',
    duration: '3 months',
    type: 'internship',
    highlights: [
      'Engineered a multimodal AI pipeline combining a large language model with MedGemma-4B to generate clinical insights from medical imaging data',
      'Led vision-language model research end-to-end: crawled & curated datasets, fine-tuned the model, and built an automated validation pipeline',
      'Designed a responsive landing page that visualizes complex AI backend outputs for researchers and stakeholders',
    ],
    technologies: ['Python', 'LangChain', 'LLM', 'VLM', 'MedGemma', 'ONNX'],
  },
  {
    id: '2',
    role: 'Full Stack Developer',
    company: 'Wanderlust — Apna College',
    location: 'Remote',
    period: 'Sep 2025 - Dec 2025',
    duration: '4 months',
    type: 'work',
    highlights: [
      'Shipped Wanderlust, a production-grade Airbnb-style accommodation platform, from a blank repository to a live product',
      'Implemented secure authentication with Passport.js, media management via Cloudinary, and interactive maps with Leaflet.js',
      'Architected a modular MVC backend with MongoDB & Express.js and REST APIs used across the entire feature set',
    ],
    technologies: ['Node.js', 'Express', 'MongoDB', 'Mongoose', 'EJS', 'Leaflet', 'Cloudinary'],
  },
  {
    id: '3',
    role: 'Hackfest 2.0 — AI Interview Platform',
    company: 'GIET Bhubaneswar',
    location: 'Bhubaneswar',
    period: 'Feb 2026',
    duration: '24 hrs',
    type: 'hackathon',
    highlights: [
      'Built an AI-powered interview-prep SaaS in a 24-hour hackathon, covering mock interviews, feedback scoring, and progress tracking',
      'Delivered a full-stack feature set while coordinating a team under tight deadline pressure',
    ],
    technologies: ['Full Stack', 'REST API', 'AI', 'SaaS'],
  },
  {
    id: '4',
    role: 'Smart Home Automation — IoT Engineer',
    company: 'Self Project',
    location: 'Home-based',
    period: 'May 2025',
    duration: '1 month',
    type: 'project',
    highlights: [
      'Built a smart-home system with ESP32 & Arduino that automates 4+ appliances through a custom web dashboard',
      'Implemented a responsive browser interface for remote monitoring and control from any device',
    ],
    technologies: ['ESP32', 'Arduino', 'MQTT', 'IoT', 'HTML/CSS', 'JavaScript'],
  },
  {
    id: '5',
    role: 'Simon Says — Memory Game',
    company: 'Self Project',
    location: '',
    period: 'Aug 2025',
    duration: '1 month',
    type: 'project',
    highlights: [
      'Developed a polished Simon Says memory game using JavaScript and vanilla DOM APIs',
      'Added a progressive difficulty and scoring system that adapts to player skill for longer play sessions',
    ],
    technologies: ['JavaScript', 'DOM', 'Events', 'CSS Animations'],
  },
  {
    id: '6',
    role: 'Spotify Clone — Music UI',
    company: 'Self Project',
    location: '',
    period: 'Jun - Jul 2025',
    duration: '2 months',
    type: 'project',
    highlights: [
      'Recreated a fully responsive Spotify-style music player with working play controls and a library view',
      'Focused on clean component structure and pixel-perfect responsive behavior across all breakpoints',
    ],
    technologies: ['HTML', 'CSS', 'JavaScript', 'Responsive Design'],
  },
]